language: python
python:
  - "2.7"

install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install flake8 coverage nose coveralls
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - flake8 .
  - python -m nose tests --with-coverage --cover-package tesseract

after_success:
  - coveralls

notifications:
  email: false
